language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2
    - os: windows

git:
  depth: 1
  submodules: false

before_install:
  - export -f travis_nanoseconds travis_time_start travis_time_finish
  - export GIT_DEPTH=$(if [ 002021000 -le $(git --version | sed -e 's#^[^0-9]*\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*$#00\1.00\2.00\3#g' -e 's#[0-9]*\([0-9]\{3\}\)\.*#\1#g') ]; then echo '--depth 1'; fi)

script:
  - if ! [ -x .cppsm/travis-ci ]; then git submodule --quiet update --init --no-recommend-shallow $GIT_DEPTH .cppsm; fi
  - .cppsm/travis-ci
